"""empty message

Revision ID: 9a60051f822f
Revises: 6f4d6753dcf1
Create Date: 2026-03-29 21:53:03.168140

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a60051f822f"
down_revision: Union[str, Sequence[str], None] = "6f4d6753dcf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "symbolmeta",
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbolmeta", "currency")
    # ### end Alembic commands ###
